### ISSUE TITLE
Bug: Spiel nicht startbar

### ISSUE THREAD

**Issue by kuihlein** [yk9301/multiplayer-ASCII#3]
Wenn man das Spiel startet, kommen nur Fehlermeldungen:
<img width="889" alt="Screenshot 2024-10-16 at 15 21 44" src="https://github.com/user-attachments/assets/31a8e078-19d3-47e3-bdd9-e4e5749945a1">

**Comment by KaiMalaka** [comment]
Durch den letzten Commit von Yannis gefixt
